regionalkecamatan_index:
    path:     /
    defaults: { _controller: "EntitasBundle:RegionalKecamatan:index" }
    methods:  GET

regionalkecamatan_show:
    path:     /{id}/show
    defaults: { _controller: "EntitasBundle:RegionalKecamatan:show" }
    methods:  GET

regionalkecamatan_new:
    path:     /new
    defaults: { _controller: "EntitasBundle:RegionalKecamatan:new" }
    methods:  [GET, POST]

regionalkecamatan_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntitasBundle:RegionalKecamatan:edit" }
    methods:  [GET, POST]

regionalkecamatan_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitasBundle:RegionalKecamatan:delete" }
    methods:  DELETE
