entitas_regionalpropinsi:
    resource: "@EntitasBundle/Resources/config/routing/regionalpropinsi.yml"
    prefix:   /{_locale}/regionalpropinsi
entitas_regionalkabupaten:
    resource: "@EntitasBundle/Resources/config/routing/regionalkabupaten.yml"
    prefix:   /{_locale}/regionalkabupaten

entitas_regionalkecamatan:
    resource: "@EntitasBundle/Resources/config/routing/regionalkecamatan.yml"
    prefix:   /{_locale}/regionalkecamatan

entitas_kelamin:
    resource: "@EntitasBundle/Resources/config/routing/kelamin.yml"
    prefix:   /{_locale}/kelamin

entitas_pendidikan:
    resource: "@EntitasBundle/Resources/config/routing/pendidikan.yml"
    prefix:   /{_locale}/pendidikan

entitas_pernikahan:
    resource: "@EntitasBundle/Resources/config/routing/pernikahan.yml"
    prefix:   /pernikahan
home_index:
    path:     /
    defaults: { _controller: EntitasBundle:Home:index }
