<?php

namespace EntitasBundle\Repositories;

/**
 * DendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionalPropinsiRepository extends \Doctrine\ORM\EntityRepository
{

    public function findKabubaptenByPropId($id)
    {
        $qb = $this->createQueryBuilder('rp');
        $qb     ->  select('rp','rkab')
                ->  innerjoin('rp.kabupatens','rkab')
                ->  where('rp.id =:id')
                ->  setParameter('id',$id)
                ->  OrderBy('rp.id');        
        return $qb->getQuery()->getArrayResult();      
    }       
	
}